import { AiFillStar } from "react-icons/ai";
const Cars = [
  {
    objectId: "DEUhkh0p7D",
    Img: "https://i.imgur.com/dykISiw.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Ferrari",
    Model: "Portofino",
    Engine: "V8",
    Doors: "2",
    Color: "red",
    Reviews: "3454 reviews",
    NewPrice: "$2000000",
    Category: "Convertible",
  },
  {
    objectId: "7f6NuNcz5Q",
    Img: "https://i.imgur.com/0OFNpR7.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Ferrari",
    Model: "F12berlinetta",
    Engine: "V12",
    Doors: "2",
    Color: "black",
    Reviews: "6754 reviews",
    NewPrice: "$2000000",
    Category: "Coupe",
  },
  {
    objectId: "nTSt68sCf3",
    Img: "https://i.imgur.com/6jY0JzV.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Ferrari",
    Model: "California",
    Engine: "V8",
    Doors: "2",
    Color: "red",
    Reviews: "5436 reviews",
    NewPrice: "$2000000",
    Category: "Convertible",
  },
  {
    objectId: "bIBwtlieZU",
    Img: "https://i.imgur.com/OLgyNlb.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Ferrari",
    Model: "488 GTB",
    Engine: "V8",
    Doors: "2",
    Color: "black",
    Reviews: "7654 reviews",
    NewPrice: "$6000000",
    Category: "Coupe",
  },
  {
    objectId: "IUk49HdN3d",
    Img: "https://i.imgur.com/r4nytyU.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "Ferrari",
    Model: "FF",
    Engine: "V12",
    Doors: "2",
    Color: "blue",
    Reviews: "3544 reviews",
    NewPrice: "$4000000",
    Category: "Coupe",
  },
  {
    objectId: "7bFb3FFwsW",
    Img: "https://i.imgur.com/DqxXKzi.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Ferrari",
    Model: "812 Superfast",
    Engine: "V12",
    Doors: "2",
    Color: "white",
    Reviews: "8756 reviews",
    NewPrice: "$6300000",
    Category: "Coupe",
  },
  {
    objectId: "FxPeJ9EFtA",
    Img: "https://i.imgur.com/SK3aEjk.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2015,
    Make: "Ferrari",
    Model: "458 Speciale",
    Engine: "V8",
    Doors: "2",
    Color: "yellow",
    Reviews: "7583 reviews",
    NewPrice: "$5800000",
    Category: "Coupe",
  },
  {
    objectId: "BE7vsIvlaZ",
    Img: "https://i.imgur.com/NXbZJ1b.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2015,
    Make: "Ferrari",
    Model: "458 Italia",
    Engine: "V8",
    Doors: "2",
    Color: "blue",
    Reviews: "8976 reviews",
    NewPrice: "$5500000",
    Category: "Coupe",
  },
  {
    objectId: "841eNXe2cp",
    Img: "https://i.imgur.com/7wzRCuf.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "Ferrari",
    Model: "488 Spider",
    Engine: "V8",
    Doors: "2",
    Color: "white",
    Reviews: "6543 reviews",
    NewPrice: "$5300000",
    Category: "Convertible",
  },
  {
    objectId: "3jCTkADJgf",
    Img: "https://i.imgur.com/FnwMD5w.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Ferrari",
    Model: "488 Spider",
    Engine: "V8",
    Doors: "2",
    Color: "yellow",
    Reviews: "8567 reviews",
    NewPrice: "$7000000",
    Category: "Convertible",
  },
  {
    objectId: "2fj2GFhbqM",
    Img: "https://i.imgur.com/pOTX4lL.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Lamborghini",
    Model: "Aventador",
    Engine: "V12",
    Doors: "2",
    Color: "yellow",
    Reviews: "5678 reviews",
    NewPrice: "$7600000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "JtACtwAQtp",
    Img: "https://i.imgur.com/QLtrRq3.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "Lamborghini",
    Model: "Aventador",
    Engine: "V12",
    Doors: "2",
    Color: "blue",
    Reviews: "6754 reviews",
    NewPrice: "$7800000",
    Category: "Convertible, Coupe",
  },
  {
    objectId: "Auyx3yAElU",
    Img: "https://i.imgur.com/ZXrADku.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "Lamborghini",
    Model: "Huracan",
    Engine: "V10",
    Doors: "2",
    Color: "red",
    Reviews: "5466 reviews",
    NewPrice: "$6000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "E8mhglrSlJ",
    Img: "https://i.imgur.com/sPfjjIa.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2015,
    Make: "Lamborghini",
    Model: "Huracan",
    Engine: "V10",
    Doors: "2",
    Color: "white",
    Reviews: "6756 reviews",
    NewPrice: "$6800000",
    Category: "Coupe",
  },
  {
    objectId: "J43AEO1Wya",
    Img: "https://i.imgur.com/skvyUcE.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2015,
    Make: "Lamborghini",
    Model: "Aventador",
    Engine: "V12",
    Doors: "2",
    Color: "black",
    Reviews: "6788 reviews",
    NewPrice: "$8000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "CvQwiiQqfH",
    Img: "https://i.imgur.com/NhLWWvZ.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Lamborghini",
    Model: "Huracan",
    Engine: "V10",
    Doors: "2",
    Color: "blue",
    Reviews: "5678 reviews",
    NewPrice: "$4000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "MyoyXpd3uO",
    Img: "https://i.imgur.com/dUUhKt3.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Lamborghini",
    Model: "Huracan",
    Engine: "V10",
    Doors: "2",
    Color: "black",
    Reviews: "5467 reviews",
    NewPrice: "$5000000",
    Category: "Coupe",
  },
  {
    objectId: "vuAcOkdMF6",
    Img: "https://i.imgur.com/DN6pj2X.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2014,
    Make: "Lamborghini",
    Model: "Aventador",
    Engine: "V12",
    Doors: "2",
    Color: "white",
    Reviews: "6789 reviews",
    NewPrice: "$5000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "mPYLA0lCwJ",
    Img: "https://i.imgur.com/nCUaYcm.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2014,
    Make: "Lamborghini",
    Model: "Gallardo",
    Engine: "V10",
    Doors: "2",
    Color: "yellow",
    Reviews: "5674 reviews",
    NewPrice: "$6000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "zGchNFd63n",
    Img: "https://i.imgur.com/ByJYVBB.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Lamborghini",
    Model: "Aventador",
    Engine: "V12",
    Doors: "2",
    Color: "red",
    Reviews: "6788 reviews",
    NewPrice: "$7000000",
    Category: "Convertible, Coupe",
  },
  {
    objectId: "aHzGLkubQV",
    Img: "https://i.imgur.com/3GzccRr.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "McLaren",
    Model: "570S",
    Engine: "V8",
    Doors: "2",
    Color: "blue",
    Reviews: "8676 reviews",
    NewPrice: "$8000000",
    Category: "Coupe",
  },
  {
    objectId: "uKnWAqjnFe",
    Img: "https://i.imgur.com/RKYyAQu.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "McLaren",
    Model: "570S",
    Engine: "V8",
    Doors: "2",
    Color: "black",
    Reviews: "5467 reviews",
    NewPrice: "$6000000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "udh64Wr38H",
    Img: "https://i.imgur.com/99Pu3br.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "McLaren",
    Model: "570GT",
    Engine: "V8",
    Doors: "2",
    Color: "white",
    Reviews: "6785 reviews",
    NewPrice: "$5000000",
    Category: "Coupe",
  },
  {
    objectId: "tLBMYaJXMb",
    Img: "https://i.imgur.com/tJisG3y.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "McLaren",
    Model: "570S",
    Engine: "V8",
    Doors: "2",
    Color: "red",
    Reviews: "5677 reviews",
    NewPrice: "$4700000",
    Category: "Coupe",
  },
  {
    objectId: "4rO7nnzTxD",
    Img: "https://i.imgur.com/7dYV09k.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "McLaren",
    Model: "650S",
    Engine: "V8",
    Doors: "2",
    Color: "yellow",
    Reviews: "6789 reviews",
    NewPrice: "$4500000",
    Category: "Convertible, Coupe",
  },
  {
    objectId: "cs4sP1pp15",
    Img: "https://i.imgur.com/9QGzJMY.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2014,
    Make: "McLaren",
    Model: "MP4-12C",
    Engine: "V8",
    Doors: "2",
    Color: "blue",
    Reviews: "5678 reviews",
    NewPrice: "$2400000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "dmtX6KQBKR",
    Img: "https://i.imgur.com/QBwMgHj.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "McLaren",
    Model: "720S",
    Engine: "V8",
    Doors: "2",
    Color: "white",
    Reviews: "4567 reviews",
    NewPrice: "$2500000",
    Category: "Coupe",
  },
  {
    objectId: "DnvzUtoFGu",
    Img: "https://i.imgur.com/jeQiWGx.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2016,
    Make: "McLaren",
    Model: "675LT",
    Engine: "V8",
    Doors: "2",
    Color: "red",
    Reviews: "5677 reviews",
    NewPrice: "$2300000",
    Category: "Coupe",
  },
  {
    objectId: "xQhA2imJUN",
    Img: "https://i.imgur.com/xwiTSZi.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "McLaren",
    Model: "570GT",
    Engine: "V8",
    Doors: "2",
    Color: "black",
    Reviews: "6789 reviews",
    NewPrice: "$2900000",
    Category: "Coupe",
  },
  {
    objectId: "69h1bnwABJ",
    Img: "https://i.imgur.com/MbIwQBk.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2015,
    Make: "McLaren",
    Model: "650S",
    Engine: "V8",
    Doors: "2",
    Color: "yellow",
    Reviews: "5674 reviews",
    NewPrice: "$2300000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "qcwTvAzvPk",
    Img: "https://i.imgur.com/K0lwXhw.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2020,
    Make: "Audi",
    Model: "R8",
    Engine: "V10",
    Doors: "2",
    Color: "white",
    Reviews: "6789 reviews",
    NewPrice: "$2200000",
    Category: "Coupe, Convertible",
  },
  {
    objectId: "rX5sNOPZJC",
    Img: "https://i.imgur.com/WBmoGfp.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Audi",
    Model: "e-tron",
    Engine: "Electric",
    Doors: "4",
    Color: "black",
    Reviews: "3546 reviews",
    NewPrice: "$1100000",
    Category: "SUV",
  },
  {
    objectId: "2CUcwBko2t",
    Img: "https://i.imgur.com/dXpt0dz.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Audi",
    Model: "Q8",
    Engine: "V6",
    Doors: "4",
    Color: "blue",
    Reviews: "3546 reviews",
    NewPrice: "$1000000",
    Category: "SUV",
  },
  {
    objectId: "BTriGIv2Gt",
    Img: "https://i.imgur.com/uNxBbEd.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Audi",
    Model: "Q5",
    Engine: "V6",
    Doors: "4",
    Color: "red",
    Reviews: "5676 reviews",
    NewPrice: "$14000000",
    Category: "SUV",
  },
  {
    objectId: "iSyJDLyhUC",
    Img: "https://i.imgur.com/3z4KwV6.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Audi",
    Model: "S5",
    Engine: "V6",
    Doors: "4",
    Color: "blue",
    Reviews: "3546 reviews",
    NewPrice: "$42000000",
    Category: "Convertible,Sedan,Coupe",
  },
  {
    objectId: "6I3A3rIyyD",
    Img: "https://i.imgur.com/bBsnEie.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Audi",
    Model: "A7",
    Engine: "V6",
    Doors: "4",
    Color: "red",
    Reviews: "5467 reviews",
    NewPrice: "$17000000",
    Category: "Sedan",
  },
  {
    objectId: "5CwQXUZwjL",
    Img: "https://i.imgur.com/oBAqRde.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2020,
    Make: "Audi",
    Model: "Q3",
    Engine: "V4",
    Doors: "4",
    Color: "yellow",
    Reviews: "3565 reviews",
    NewPrice: "$13000000",
    Category: "SUV",
  },
  {
    objectId: "z77pwHdar1",
    Img: "https://i.imgur.com/w6CJMny.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Audi",
    Model: "A8",
    Engine: "V6",
    Doors: "4",
    Color: "black",
    Reviews: "5678 reviews",
    NewPrice: "$13000000",
    Category: "Sedan",
  },
  {
    objectId: "HOdIAHYt2O",
    Img: "https://i.imgur.com/qA1dbFi.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Audi",
    Model: "Q7",
    Engine: "V6",
    Doors: "4",
    Color: "white",
    Reviews: "3564 reviews",
    NewPrice: "$11000000",
    Category: "SUV",
  },
  {
    objectId: "ANqQvSwFry",
    Img: "https://i.imgur.com/x1MHa8w.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Audi",
    Model: "A3",
    Engine: "V4",
    Doors: "2",
    Color: "red",
    Reviews: "5546 reviews",
    NewPrice: "$10000000",
    Category: "Convertible, Sedan",
  },
  {
    objectId: "cgX0LNXp7Y",
    Img: "https://i.imgur.com/QPcxlx4.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2022,
    Make: "Nissan",
    Model: "Pathfinder",
    Engine: "V6",
    Doors: "4",
    Color: "red",
    Reviews: "4324 reviews",
    NewPrice: "$500000",
    Category: "SUV",
  },
  {
    objectId: "wXEmjGsY9S",
    Img: "https://i.imgur.com/ntc6L2e.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Nissan",
    Model: "Rogue",
    Engine: "V3",
    Doors: "4",
    Color: "black",
    Reviews: "3244 reviews",
    NewPrice: "$400000",
    Category: "SUV",
  },
  {
    objectId: "YaiwBhaquU",
    Img: "https://i.imgur.com/twD67GY.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Nissan",
    Model: "Maxima",
    Engine: "V6",
    Doors: "4",
    Color: "blue",
    Reviews: "3244 reviews",
    NewPrice: "$500000",
    Category: "Sedan",
  },
  {
    objectId: "uay8zhuc9h",
    Img: "https://i.imgur.com/BnM4CkM.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2020,
    Make: "Nissan",
    Model: "GT-R",
    Engine: "V6",
    Doors: "2",
    Color: "white",
    Reviews: "8967 reviews",
    NewPrice: "$750000",
    Category: "Coupe",
  },
  {
    objectId: "aVZqFsQ312",
    Img: "https://i.imgur.com/CVClSoC.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2020,
    Make: "Nissan",
    Model: "370Z",
    Engine: "V6",
    Doors: "2",
    Color: "yellow",
    Reviews: "3254 reviews",
    NewPrice: "$300000",
    Category: "Coupe",
  },
  {
    objectId: "SH6mip0Oro",
    Img: "https://i.imgur.com/wkUFS0r.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Tesla",
    Model: "Model 3",
    Engine: "Electric",
    Doors: "4",
    Color: "white",
    Reviews: "6785 reviews",
    NewPrice: "$3300000",
    Category: "Sedan",
  },
  {
    objectId: "1EMRcGRHTe",
    Img: "https://i.imgur.com/L4yicSz.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Tesla",
    Model: "Model X",
    Engine: "Electric",
    Doors: "4",
    Color: "black",
    Reviews: "3546 reviews",
    NewPrice: "$3400000",
    Category: "SUV",
  },
  {
    objectId: "WoDeIHZjJE",
    Img: "https://i.imgur.com/OjFDtJR.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Tesla",
    Model: "Model S",
    Engine: "Electric",
    Doors: "4",
    Color: "blue",
    Reviews: "5677 reviews",
    NewPrice: "$2700000",
    Category: "Sedan",
  },
  {
    objectId: "RgF7JiK7s3",
    Img: "https://i.imgur.com/wZXQoOj.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Tesla",
    Model: "Model S",
    Engine: "Electric",
    Doors: "4",
    Color: "red",
    Reviews: "3546 reviews",
    NewPrice: "$2500000",
    Category: "Sedan",
  },
  {
    objectId: "O1iqTzwSl2",
    Img: "https://i.imgur.com/1jtJ7Te.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2019,
    Make: "Tesla",
    Model: "Model 3",
    Engine: "Electric",
    Doors: "4",
    Color: "yellow",
    Reviews: "4567 reviews",
    NewPrice: "$2100000",
    Category: "Sedan",
  },
  {
    objectId: "prhqD3t2kX",
    Img: "https://i.imgur.com/x6P2SXY.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Tesla",
    Model: "Model X",
    Engine: "Electric",
    Doors: "4",
    Color: "black",
    Reviews: "5678 reviews",
    NewPrice: "$2000000",
    Category: "SUV",
  },
  {
    objectId: "SpVywl0RPX",
    Img: "https://i.imgur.com/SXvYLq4.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2017,
    Make: "Tesla",
    Model: "Model S",
    Engine: "Electric",
    Doors: "4",
    Color: "white",
    Reviews: "3546 reviews",
    NewPrice: "$2100000",
    Category: "Sedan",
  },
  {
    objectId: "iOZw22ym5F",
    Img: "https://i.imgur.com/eBjcLkF.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2018,
    Make: "Tesla",
    Model: "Model X",
    Engine: "Electric",
    Doors: "4",
    Color: "red",
    Reviews: "6789 reviews",
    NewPrice: "$2800000",
    Category: "SUV",
  },
  {
    objectId: "YGYHcyXvfO",
    Img: "https://i.imgur.com/EGClSzz.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Tesla",
    Model: "Model X",
    Engine: "Electric",
    Doors: "4",
    Color: "black",
    Reviews: "8977 reviews",
    NewPrice: "$4300000",
    Category: "SUV",
  },
  {
    objectId: "LwH8Kwr6x7",
    Img: "https://i.imgur.com/y0Zt8SS.png",
    Star: <AiFillStar className="rating-star text-yellow-400" />,
    Year: 2021,
    Make: "Tesla",
    Model: "Model S",
    Engine: "Electric",
    Doors: "4",
    Color: "red",
    Reviews: "8679 reviews",
    NewPrice: "$4200000",
    Category: "Sedan",
  },
];

export default Cars;
